test compile
set colocated_libcalls=1
set probestack_func_adjusts_sp=1
target x86_64

; Like @big in probestack.clif, but with the probestack function adjusting
; the stack pointer itself.

function @big() system_v {
    ss0 = explicit_slot 300000
ebb0:
    return
}
; check: function @big(i64 fp [%rbp]) -> i64 fp [%rbp] system_v {
; nextln:    ss0 = explicit_slot 300000, offset -300016
; nextln:    ss1 = incoming_arg 16, offset -16
; nextln:    sig0 = (i64 [%rax]) probestack
; nextln:    fn0 = colocated @<Probestack> sig0
; nextln: 
; nextln:                                 ebb0(v0: i64 [%rbp]):
; nextln: [RexOp1pushq#50]                    x86_push v0
; nextln: [RexOp1copysp#8089]                 copy_special %rsp -> %rbp
; nextln: [RexOp1pu_id#b8,%rax]               v1 = iconst.i64 0x0004_93e0
; nextln: [Op1call_id#e8]                     call fn0(v1)
; nextln: [RexOp1adjustsp_id#8081]            adjust_sp_up_imm 0x0004_93e0
; nextln: [RexOp1popq#58,%rbp]                v2 = x86_pop.i64
; nextln: [Op1ret#c3]                         return v2
; nextln: }
