; Test the legalization of i32 instructions that don't have RISC-V versions.
test legalizer

target riscv32 supports_m=1

target riscv64 supports_m=1

; regex: V=v\d+

function @carry_out(i32, i32) -> i32, b1 {
ebb0(v1: i32, v2: i32):
    v3, v4 = iadd_cout v1, v2
    return v3, v4
}
; check: v3 = iadd v1, v2
; check: v4 = icmp ult v3, v1
; check: return v3, v4

; Expanding illegal immediate constants.
; Note that at some point we'll probably expand the iconst as well.
function @large_imm(i32) -> i32 {
ebb0(v0: i32):
    v1 = iadd_imm v0, 1000000000
    return v1
}
; check: $(cst=$V) = iconst.i32 0x3b9a_ca00
; check: v1 = iadd v0, $cst
; check: return v1

function @bitclear(i32, i32) -> i32 {
ebb0(v0: i32, v1: i32):
    v2 = band_not v0, v1
    ; check: iconst.i32 -1
    ; check: bxor
    ; check: band
    return v2
}
